apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: default
  labels:
    k8s-app: fluentd-logging
    version: v1
    #kubernetes.io/cluster-service: "true"
spec:
  selector:
    matchLabels:
      k8s-app: fluentd-logging
      version: v1  
  template:
    metadata:
      labels:
        k8s-app: fluentd-logging
        version: v1
        #kubernetes.io/cluster-service: "true"
    spec:
      serviceAccount: fluentd
      serviceAccountName: fluentd
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: fluentd
        #image: fluent/fluentd-kubernetes-daemonset:v1.3-debian-elasticsearch
        #image: fluent/fluentd-kubernetes-daemonset:v1-debian-elasticsearch
        image: quay.io/fluent/fluentd-kubernetes-daemonset
        #image: fluent/fluentd-kubernetes-daemonset:elasticsearch
        env:
          - name:  FLUENT_ELASTICSEARCH_HOST
            #value: "elasticsearch.logging"
            #value: "elastic-operator-0"
            #value: "10.96.240.152"
            #value: "quickstart-es-http.default.svc.cluster.local"
            value: "quickstart-es-http"
          - name:  FLUENT_ELASTICSEARCH_PORT
            value: "9200"
          - name: FLUENT_ELASTICSEARCH_SCHEME
            value: "https"
          - name: FLUENT_ELASTICSEARCH_SSL_VERIFY
            value: "false"
          - name: FLUENT_ELASTICSEARCH_SSL_VERSION
            value: "TLSv1_2"
          - name: FLUENT_UID
            value: "0"
          - name: FLUENT_ELASTICSEARCH_USER
            value: "elastic"
          - name: FLUENT_ELASTICSEARCH_PASSWORD
            value: "hGCOe6c72n2q28b0DTB51pp2"
          - name: FLUENTD_SYSTEMD_CONF
            value: disable    
          - name: FLUENT_ELASTICSEARCH_CA_FILE
            value: "/k8s-elastic-fs/tls.crt"    
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: es-certs
          mountPath: /k8s-elastic-fs/tls.crt
          readOnly: true
          subPath: tls.crt

      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: es-certs 
        #hostPath:
         # path: /k8s-elastic-fs/tls.crt
        secret:
          secretName: quickstart-es-http-certs-public
